# obligatory fields

name: tbd
version: git
summary: A simple version control system built on top of Git
description: |
  tbd is an experimental version control system built on top of Git.
  Many people complain that Git is hard to use. We think the problem lies
  deeper than the user interface, in the concepts underlying Git. tbd
  is an experiment to see what happens if you put a simple veneer on an
  app that changes the underlying concepts. Because tbd is implemented
  on top of Git (could be considered what Git pros call a "porcelain" of
  Git), you can always fall back on Git. And of course your coworkers you
  share a repo with need never know that you're not a Git aficionado.

grade: devel          # 'stable' for stable/candidate upload
confinement: devmode  # 'strict' after right plugs and slots

# 'optional' fields

apps:
  tbd:
    command: bin/tbd

parts:
  libgit2:
    plugin: cmake
    source: https://github.com/libgit2/libgit2/archive/v0.27.0.tar.gz
    build-packages:
      - libssl-dev

  tbd-cli:
    plugin: python
    source: .
    after: [libgit2]
    # need git until https://github.com/sdg-mit/tbd/issues/176
    stage-packages:
      - git
    build-packages:
      - git
      
